services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./volume/redis_data:/data
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./volume/mongo_data:/data/db
    networks:
      - app_network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_DATABASE: 
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./volume/mysql_data:/var/lib/mysql:rw
    networks:
      - app_network
    user: mysql
  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./volume/jupyter_data:/home/jovyan/work
    networks:
      - app_network
    environment:
      JUPYTER_TOKEN: developer
volumes:
  redis_data:
  mongo_data:
  mysql_data:
  jupyter_data:
networks:
  app_network: